version: 1.0

services:
  app:
    build: 
      command: make build
    entrypoint: "./main"
    assets: 
      - "./public"
      - "./main"
    env:
      - name: "ENV_VAR"
        value: "123"
    env_file:
      - .env
